require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-config/ios/ReactNativeConfig/ReactNativeConfig.rb'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Nếu bạn muốn sử dụng nhiều target khác nhau cho dev và prod
abstract_target 'App' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
  )

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'FirstRna' do
    # Development target
    target 'FirstRna-Development' do
      inherit! :complete
    end

    # Production target
    target 'FirstRna-Production' do
      inherit! :complete
    end
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
